# Generated by Django 4.2.2 on 2023-06-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.account', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('user_media', models.FileField(upload_to='uploads/medias/', verbose_name='Media')),
                ('alt', models.CharField(max_length=100, verbose_name='Alter')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('is_like', models.BooleanField(verbose_name='like/dislike')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', verbose_name='User')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('tag', models.SlugField(unique=True, verbose_name='Hashtag')),
                ('user_post', models.ManyToManyField(related_name='tags', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Hashtag',
                'verbose_name_plural': 'Hashtags',
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('content', models.TextField(verbose_name='Comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comments', verbose_name='Parent')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post ID')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Commentss',
            },
            bases=('core.basemodel',),
        ),
    ]
