# Generated by Django 4.2.2 on 2023-06-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0002_alter_account_options'),
        ('posts', '0002_remove_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=True, verbose_name='like/dislike'),
        ),
    ]
