# Generated by Django 4.2.2 on 2023-06-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_hashtag_user_post_hashtag_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='user_post',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='user_post',
            field=models.ManyToManyField(related_name='tags', to='posts.post', verbose_name='Post'),
        ),
    ]
