# Generated by Django 4.2.2 on 2023-06-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_hashtag_user_post_hashtag_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alt',
            field=models.CharField(default='not found', max_length=100, verbose_name='Alter'),
        ),
    ]
