# Generated by Django 4.2.2 on 2023-07-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_media_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.SlugField(verbose_name='Hashtag'),
        ),
    ]
