# Generated by Django 4.2.2 on 2023-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_hashtag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.SlugField(unique=True, verbose_name='Hashtag'),
        ),
    ]
