# Generated by Django 4.2.2 on 2023-07-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_hashtag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='user_media',
            field=models.FileField(blank=True, upload_to='uploads/medias/', verbose_name='Media'),
        ),
    ]
