# Generated by Django 4.2.2 on 2023-07-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_media_user_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRecycle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
    ]
