# Generated by Django 4.2.2 on 2023-07-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postrecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrecycle',
            options={'verbose_name': 'Recycle Post', 'verbose_name_plural': 'Recycle Posts'},
        ),
    ]
