# Generated by Django 4.2.2 on 2023-07-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Is_Active'),
        ),
    ]
