# Generated by Django 4.2.2 on 2023-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='/uploads/avatar/default.png', upload_to='uploads/avatars/', verbose_name='Avatar'),
        ),
    ]
