# Generated by Django 4.2.2 on 2023-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='uploads/avatars/default.png', upload_to='uploads/avatars/', verbose_name='Avatar'),
        ),
    ]
