# Generated by Django 4.2.2 on 2023-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatars/default.jpg', null=True, upload_to='uploads/avatars/', verbose_name='Avatar'),
        ),
    ]
