# Generated by Django 4.2.2 on 2023-06-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('avatar', models.ImageField(upload_to=None, verbose_name='Avatar')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('password', models.CharField(max_length=250, verbose_name='Password hass')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('core.basemodel',),
        ),
    ]
